<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aequitas.Core\Aequitas.Core.csproj" />
    <ProjectReference Include="..\Aequitas.Infrastructure\Aequitas.Infrastructure.csproj" />
  </ItemGroup>

</Project>
